### ISSUE TITLE
Icalendar feed

### ISSUE THREAD

**Issue by SamGuay** [BrainhackMTL/school#26]
There is a problem with the .ics feed found at webcal://school.brainhackmtl.org/schedule/index.ics. 

It seems to be a problem related to Line 1, but I can't find out why. 

```
Lines not delimited by CRLF sequence near line # 1
Reference: RFC 5545 3.1. Content Lines
```

> The iCalendar object is organized into individual lines of text, called content lines. Content lines are delimited by a line break, which is a CRLF sequence (CR character followed by LF character).

[Related thread on SO](https://stackoverflow.com/questions/33648182/online-ical-feed-wont-work), but in PHP so I don't know what to do next. try to implement `\r\n` after each line?

@gkiar, do you have any idea since you are the pro of .ical feed?

**Comment by gkiar** [comment]
@SamGuay can you point me to how we're generating the feed, if it's quick? (just to save me bouncing around looking for it). I think despite calendars that I've generated in the past not passing this validation, they still are functional in calendar apps I've tested (this is the case for https://raw.githubusercontent.com/gkiar/ical-cli/master/example_calendar.ics, for example).

Is the calendar failing to import, or have you not tried because it fails validation?

**Comment by SamGuay** [comment]
Thanks for looking into this! 

So I generate the .ics based on the /data/en/schedule.yaml file. You can find the template in layouts/schedule/single.ics. It only ranges through all the 'sessions' for each day. 

I'll send the .ics file to you on GH. I can import it, but nothing is showing up :shrug: .

**Comment by SamGuay** [comment]
Here's the validator and the feed: 
https://icalendar.org/validator.html?url=http://school.brainhackmtl.org/schedule/index.ics
